// OPTIONS DIALOG MACROS

// Macro IDC's
#define IDD_OPTIONS 4050

#define IDC_OPTIONSDIALOG_BACKGROUND 4051
#define IDC_OPTIONSDIALOG_TEXT_TITLE 4052

#define IDC_OPTIONSDIALOG_TEXT_TIME 4053
#define IDC_OPTIONSDIALOG_TEXT_WEATHER 4054
#define IDC_OPTIONSDIALOG_TEXT_FORECAST 4055
#define IDC_OPTIONSDIALOG_TEXT_AA_CHANCE 4056
#define IDC_OPTIONSDIALOG_TEXT_CAS_CHANCE 4057
#define IDC_OPTIONSDIALOG_TEXT_CAS_RESPONSE 4058
#define IDC_OPTIONSDIALOG_TEXT_MECH_CHANCE 4059
#define IDC_OPTIONSDIALOG_TEXT_MECH_PREFER 4060

#define IDC_OPTIONSDIALOG_FRAME_MISSION 4061
#define IDC_OPTIONSDIALOG_FRAME_ENEMY 4062
#define IDC_OPTIONSDIALOG_FRAME_MECH 4063

#define IDC_OPTIONSDIALOG_CB_TIME 4064
#define IDC_OPTIONSDIALOG_CB_WEATHER 4065
#define IDC_OPTIONSDIALOG_CB_FORECAST 4066
#define IDC_OPTIONSDIALOG_CB_AA_CHANCE 4067
#define IDC_OPTIONSDIALOG_CB_CAS_CHANCE 4068
#define IDC_OPTIONSDIALOG_CB_CAS_RESPONSE 4069
#define IDC_OPTIONSDIALOG_CB_MECH_CHANCE 4070
#define IDC_OPTIONSDIALOG_CB_MECH_PART 4071

#define IDC_OPTIONSDIALOG_BUTTON_OK 4072