sleep 15;
titletext ["Lt Dane: Alright gentlemen, welcome to sniper school. I am Lt Dane and I will be your master training instructor for the remainder of this course", "PLAIN DOWN", 2];
sleep 10;
titletext ["Lt Dane: What you little punks have just joined is the most excruciating and extreme training program the US Army can provide. Here you will be trained to become effective killers, able to put a round in the heart of a target at ranges of up to 900m.", "PLAIN DOWN", 2];
sleep 15;
titletext ["Lt Dane: Here you will learn how to stalk a target while countless men search the area without being seen", "PLAIN DOWN", 2];
sleep 10;
titletext ["Lt Dane: Now some of you who came here may think that this is just about shooting targets and being a goodshot, but that is NOT how it works here. Here at sniper school, our soldiers spend a rigorious two weeks preparing themselves for the battlefield.", "PLAIN DOWN", 2];
sleep 20;
titletext ["Lt Dane: Here at sniper school, men are trained to become nothing - they do NOT exist. Because if a sniper DOES exist then he is a DEAD sniper, and thats not how we roll.", "PLAIN DOWN", 2];
sleep 10;
titletext ["Lt Dane: Now Personally, I dont believe snipers exist - there a conspiracy theory like UFO's / aliens and bigfoot - people claim to have seen them, but they always vanish at the moment of truth.", "PLAIN DOWN", 2];
sleep 10;
titletext ["Lt Dane: And thats what you guys are gonna become at this school - invisible and able to strike a target at nearly any range with supreme accuracy.", "PLAIN DOWN", 2];
sleep 10;
titletext ["Lt Dane: Alright, thats it for philosophy lesson. Its time we move on to actual training.", "PLAIN DOWN", 2];
sleep 5;
titletext ["Lt Dane: We'll start with the firing range - I want everyone to grab a rifle, find a spot and move up to those firing positions right behind me.", "PLAIN DOWN", 2];
donelesson = true;
sleep 5;
hint "Move to the firing position with a white flag. When you are ready for testing, use the 'finish practice' action in your menu";
